### ISSUE TITLE
Unit test task1

### ISSUE THREAD

**Issue by Vladnev** [pdffiller/react-school-entrants-tasks-php#1]
Юнит тест первого таска не работает на неотсортированном выходном массиве.
Нужно в функции `diff`
`!strcmp(serialize($arr1), serialize($arr2))`
Заменить на:
`empty(array_filter(array_map('array_diff_assoc', $arr1, $arr2)))`

**Comment by karnyushin-sergey** [comment]
Плюс один. У меня та же фигня. Приходится в 2 прохода заполнять массив, а можно в 1.

**Comment by DScheglov** [comment]
https://github.com/pdffiller/react-school-entrants-tasks-php/pull/2
